config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('resume.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

resume/urls.py
from django.urls import path
from . import views


app_name = 'resume'
urlpatterns = [
    path('', views.main_page, name='main_page'),

    #paths for working with Position object
    path('create-cv-position/', views.create_cv_position, name='create_cv_position'),
    path('htmx/contact/<int:pos_id>/update/', views.update_position, name='update_position'),
    path('htmx/position/<int:pos_id>', views.detail_position, name='detail_position'),


    path('<str:username>/create-cv-pers-data/', views.create_cv_personal_data, name='create_cv_personal_data'),

    # paths for working with Contacts objects
    path('create-cv-contacts/<int:pk>', views.create_cv_contacts, name='create_cv_contacts'),
    path('htmx/contact/<pk>/', views.detail_contact, name="detail-contact"),
    path('htmx/contact/<pk>/update/', views.update_contact, name="update-contact"),
    path('htmx/contact/<pk>/delete/', views.delete_contact, name="delete-contact"),
    path('htmx/create-contact-form/<int:pk>/', views.create_contact_form, name='create-contact-form'),

    # paths for working with Skills objects
    path('create-cv-skills/<int:pk>', views.create_cv_skills, name='create_cv_skills'),
    path('htmx/skill/<pk>/', views.detail_skill, name="detail-skill"),
    path('htmx/skill/<pk>/update/', views.update_skill, name="update-skill"),
    path('htmx/skill/<pk>/delete/', views.delete_skill, name="delete-skill"),
    path('htmx/create-skill-form/<int:pk>/', views.create_skill_form, name='create-skill-form'),

    # paths for working with WorWorkExperience objects during creating CV
    path('create-cv-workexp/<int:pk>/', views.create_cv_workexp, name='create_cv_workexp'),
    path('htmx/workexp/<int:pk>/', views.detail_workexp, name="detail-workexp"),
    path('htmx/workexp/<int:pk>/update/', views.update_workexp, name="update-workexp"),
    path('htmx/workexp/<int:pk>/delete/', views.delete_workexp, name="delete-workexp"),
    path('htmx/create-workexp-form/<int:pk>/', views.create_workexp_form, name='create-workexp-form'),

    # paths for working with Referncess objects during creating CV
    path('create-cv-references/<int:pk>/', views.create_cv_references, name='create_cv_references'),
    path('htmx/reference/<int:pk>/', views.detail_reference, name="detail-reference"),
    path('htmx/reference/<int:pk>/update/', views.update_reference, name="update-reference"),
    path('htmx/reference/<int:pk>/delete/', views.delete_reference, name="delete-reference"),
    path('htmx/create-reference-form/<int:pk>/', views.create_reference_form, name='create-reference-form'),

    path('my-all-cv', views.get_all_cv, name='get_all_cv'),
    path('detail-cv/<int:pos_id>', views.get_detail_cv, name='get_detail_cv'),
]

users/urls.py
from django.urls import path, include

from users.views import Register

urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('register/', Register.as_view(), name='register'),
]

resume/forms.py
from users.models import User
from django import forms
from django.forms import ModelForm
import resume.models
import users
from django.forms.models import inlineformset_factory


class CreateCVPositionForm(ModelForm):
    ''' Создает форму для позиции '''
    
    class Meta:
        model = resume.models.Position
        fields = '__all__'
        exclude = ('created_by', )


class CreateCVPersonalDataForm(ModelForm):
    ''' Создает форму для персональных данных '''
    
    class Meta:
        model = resume.models.PersonalData
        fields = ('first_name', 'last_name')


class CreateCVContactForm(forms.ModelForm):
    ''' form for COntacts object '''

    class Meta:
        model = resume.models.Contacts
        fields = (
            'contact_label',
            'contact_value'
        )


class CreateCVSkillForm(forms.ModelForm):
    ''' form for Skills object '''

    class Meta:
        model = resume.models.Skills
        fields = ('skill', )


class CreateCVWorkExperienceForm(forms.ModelForm):
    ''' form for WorkExperience object '''

    class Meta:
        model = resume.models.WorkExperience
        fields = ('company',
                  'position_work',
                  'link_company',
                  'date_of_employment',
                  'date_of_dismissal',
                  'description')
        

class CreateCVReferencesForm(forms.ModelForm):
    ''' form for References object '''

    class Meta:
        model = resume.models.References
        fields = ('ref_name',
                  'ref_link')

resume/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseNotAllowed, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import *

from .forms import (
    CreateCVPositionForm,
    CreateCVContactForm,
    CreateCVSkillForm,
    CreateCVPersonalDataForm,
    CreateCVWorkExperienceForm,
    CreateCVReferencesForm,
)

from my_feedback.forms import FeedBackForm
import resume.forms
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.forms.models import modelformset_factory


menu = {
    'create_cv': 'Create CV'
}

def main_page(request):
    ''' Рендерит главную страницу '''

    form = FeedBackForm
    username = request.user.username

    # количество посещений
    # num_visits = request.session.get('num_visits', 0)
    # request.session['num_visits'] = num_visits + 1

    context = {
        'menu': menu,
        'title': 'Main page',
        'form': form,
        'username': username}
    
    return render(request, 'resume/main_page.html', context=context)


@login_required(login_url='/users/login/')
def create_cv_position(request):
    ''' ренедрит форму для внесения позиции '''

    username = request.user.username
    
    if request.method == 'POST':
        position_form = resume.forms.CreateCVPositionForm(request.POST)
        if position_form.is_valid():
            position_form = position_form.save(commit=False)
            position_form.created_by = request.user
            position_form.save()
            return redirect('resume:create_cv_personal_data', username)

    position_form = CreateCVPositionForm()
    context = {
        'position_form': position_form,
        'username': username}

    return render(request, "resume/create_cv_position.html", context)


def update_position(request, pos_id):
    position = get_object_or_404(Position, id=pos_id)
    position_form = CreateCVPositionForm()

    if request.method == 'POST':
        if position_form.is_valid():
            position_form.save()

    context = {
        'position': position,
        'position_form': position_form
    }

    return render(request, 'resume/partials/position_form.html', context)


def detail_position(request, pos_id):
    position = get_object_or_404(Position, id=pos_id)

    context = {
        'position': position
    }

    return render(request, 'resume/partials/position_detail.html', context)


@login_required(login_url='/users/login/')
def create_cv_personal_data(request, username):
    ''' Получает поля из всех моделей для формы / создания резюме '''

    username = request.user.username
    last_pos = Position.objects.all().last()
    
    if request.method == 'POST':
        pers_form = resume.forms.CreateCVPersonalDataForm(request.POST)
        if pers_form.is_valid():
            pers_form = pers_form.save(commit=False)
            pers_form.pos = last_pos
            pers_form.save()
            # TODO: удалить дубликаты
            return redirect('resume:create_cv_contacts', pk=last_pos.id)

    pers_form = resume.forms.CreateCVPersonalDataForm()
    context = {
        'pers_form': pers_form}

    return render(request, "resume/create_cv_personal_data.html", context)


@login_required(login_url='/users/login/')
def create_cv_contacts(request, pk):
    ''' functions for working with models.Contacts '''

    position = Position.objects.get(id=pk)
    contacts = Contacts.objects.filter(pos=position)
    form = CreateCVContactForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            contact = form.save(commit=False)
            contact.pos = position
            contact.save()
            pk = contact.pk
            return redirect("resume:detail-contact", pk) # here i do redirect
        else:
            return render(request, "resume/partials/contact_form.html", context={
                "form": form
            })

    context = {
        "form": form,
        "position": position,
        "contacts": contacts,
        'title': 'Add contacts'
    }

    return render(request, "resume/create_cv_contacts.html", context)


@login_required(login_url='/users/login/')
def update_contact(request, pk):
    contact = Contacts.objects.get(id=pk)
    form = CreateCVContactForm(request.POST or None, instance=contact)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("resume:detail-contact", pk=contact.id)

    context = {
        "form": form,
        "contact": contact
    }

    return render(request, "resume/partials/contact_form.html", context)


@login_required(login_url='/users/login/')
def delete_contact(request, pk):
    contact = get_object_or_404(Contacts, id=pk)

    if request.method == "POST":
        contact.delete()
        return HttpResponse("")

    return HttpResponseNotAllowed(
        [
            "POST",
        ]
    )


@login_required(login_url='/users/login/')
def detail_contact(request, pk):
    ''' view for rendering added Contact to DB and displaying it on 'resume/create_cv_contact.html' template '''

    contact = get_object_or_404(Contacts, pk=pk)
    context = {
        "contact": contact
    }
    return render(request, "resume/partials/contact_detail.html", context)


@login_required(login_url='/users/login/')
def create_contact_form(request, pk):
    form = CreateCVContactForm()
    position = {"id": pk}
    context = {
        "form": form,
        "position": position,
    }
    return render(request, "resume/partials/contact_form.html", context)



''' views for working with Skills object during creating CV using forms '''

@login_required(login_url='/users/login/')
def create_cv_skills(request, pk):
    ''' main views for displaying form for to add skills to CV and redirect to HTMX template '''

    position = Position.objects.get(id=pk)
    skills = Skills.objects.filter(pos=position)
    form = CreateCVSkillForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            skill = form.save(commit=False)
            skill.pos = position
            skill.save()
            pk = skill.pk
            return redirect("resume:detail-skill", pk)
        else:
            return render(request, "resume/partials/skill_form.html", context={
                "form": form
            })

    context = {
        "form": form,
        "position": position,
        "skills": skills,
        'title': 'Add skills'
    }

    return render(request, "resume/create_cv_skills.html", context)


@login_required(login_url='/users/login/')
def create_skill_form(request, pk):
    ''' view for rendering form of instnce of Skills object for adding skills during creating CV '''

    form = CreateCVSkillForm()
    position = {"id": pk}
    context = {
        "form": form,
        "position": position,
    }
    return render(request, "resume/partials/skill_form.html", context)


@login_required(login_url='/users/login/')
def detail_skill(request, pk):
    ''' view for rendering added skill to DB and displaying it on 'resume/create_cv_skills.html' template '''

    skill = get_object_or_404(Skills, pk=pk)
    context = {
        "skill": skill
    }
    return render(request, "resume/partials/skill_detail.html", context)


@login_required(login_url='/users/login/')
def update_skill(request, pk):
    ''' view for updating added skill '''

    skill = Skills.objects.get(id=pk)
    form = CreateCVSkillForm(request.POST or None, instance=skill)
    position = {'id': skill.pos_id}
    print(position)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("resume:detail-skill", pk=skill.id)

    context = {
        "form": form,
        "skill": skill,
        'position': position
    }

    return render(request, "resume/partials/skill_form.html", context)


@login_required(login_url='/users/login/')
def delete_skill(request, pk):
    ''' view for delete instance of Skills object '''

    skill = get_object_or_404(Skills, id=pk)

    if request.method == "POST":
        skill.delete()
        return HttpResponse("")

    return HttpResponseNotAllowed(
        [
            "POST",
        ]
    )




''' views for working with WorkExperience object during creating CV using forms '''

@login_required(login_url='/users/login/')
def create_cv_workexp(request, pk):
    ''' main views for displaying form for to add WorkExperience to CV and redirect to HTMX template '''

    position = Position.objects.get(id=pk)
    workexps = WorkExperience.objects.filter(pos=position)
    form = CreateCVWorkExperienceForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            workexp = form.save(commit=False)
            workexp.pos = position
            workexp.save()
            pk = workexp.pk
            return redirect("resume:detail-workexp", pk=pk)
        else:
            return render(request, "resume/partials/workexp_form.html", context={
                "form": form,
                'position': position
            })

    context = {
        "form": form,
        "position": position,
        "workexps": workexps,
        'title': 'Add company'
    }

    return render(request, "resume/create_cv_workexp.html", context)


@login_required(login_url='/users/login/')
def create_workexp_form(request, pk):
    ''' view for rendering form of WorkExperience object for adding instnce during creating CV '''

    form = CreateCVWorkExperienceForm()
    position = {"id": pk}
    context = {
        "form": form,
        "position": position,
    }
    return render(request, "resume/partials/workexp_form.html", context)


@login_required(login_url='/users/login/')
def detail_workexp(request, pk):

resume/templates/resume/all_cv.html
{% extends 'resume/base.html' %}

{% block content %}

    <div>
        {% for cv in all_cv %}
            <div>
                <a href="{% url 'resume:get_detail_cv' cv.id %}">
                    <p>{{ cv.position_name }}</p>
                    <p>Created: {{ cv.date_create }}</p>
                </a>
            </div>
        {% endfor %}    
    </div>    

{% endblock content %}

resume/templates/resume/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://unpkg.com/htmx.org@1.9.2"></script>
    <script src="https://unpkg.com/htmx.org@1.5.0"
        integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI"
        crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="{% static 'resume/css/styles.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

    <nav class="navbar bg-body-tertiary">
        <form class="container-fluid justify-content-start">
            <div class="container text-center">
                <div class="row row-navbar">
                    <a href="{% url 'resume:main_page' %}">Logo</a> 
                    <div class="col">
                        <button type="button" class="btn btn-outline-primary">{{ menu.create_cv }}</button>
                    </div>
                    <div class="col">
                        {% if user.is_authenticated %}
                            <div class="btn-group">
                                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                Right-aligned menu example
                                </button>
                                <ul class="dropdown-menu dropdown-menu-end">
                                <li><a class="dropdown-item" href="{% url 'resume:get_all_cv' %}">My cv's</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><button class="dropdown-item" type="button">Another action</button></li>
                                <li><button class="dropdown-item" type="button">Something else here</button></li>
                                </ul>
                            </div>
                            <a href="{% url 'logout' %}">
                                <button type="button" class="btn btn-outline-primary">Logout</button>
                            </a>
                        {% else %}
                        <a href="{% url 'login' %}?next={{ request.path }}">
                            <button type="button" class="btn btn-outline-primary">Log in</button>
                        </a>
                        <a href="{% url 'register' %}">
                            <button type="button" class="btn btn-outline-primary">Sign Up</button>
                        </a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </form>
    </nav>

    <hr class="container">

    {% if messages %}
        	{% for message in messages %}
          	<div class="alert alert-{{ message.tags }}">
            	{{ message }}
          	</div>
        	{% endfor %}
    {% endif %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>   
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

resume/templates/resume/create_cv_contacts.html
{% extends 'resume/base.html' %}
{% load static %}

{% block content %}

    <div class="md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                Add contacts for {{ position.position_name }}
            </h2>
            <p>You can add your mail, phoe, telegram and more</p>
        </div>
        <div class="mt-4 flex md:mt-0 md:ml-4">
            <button type="button" hx-get="{% url 'resume:create-contact-form' position.id %}" hx-target="#contactforms" hx-swap="beforeend"
                class="ml-3 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Add form
            </button>
        </div>
    </div>


    <div id="contactforms" class="py-5 mt-5"></div>

    <div class="mt-5 py-5 border-t border-gray-100">
        {% for contact in contacts %}

        {% include "resume/partials/contact_detail.html" %}

        {% endfor %}
        
    </div>
    <div class="container">
        <a href="{% url 'resume:create_cv_skills' position.pk %}">
            <button>Next</button>
        </a>
    </div>








        <!-- {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button> -->
        
        <!-- {% for field in form %}
            <div>
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text }}</p>
            {% endif %}
            </div>
        {% endfor %}
        {{ form.as_p }} -->



        
        <!-- {% if formset %}
            <h3>Contacts</h3>
            {{ formset.management_form }}
            {% csrf_token %}

            <div id="contact-form-list">
                {% for form in formset %}
                    {{ formset.management_form }}
                    {{ form.errors }}
                    {{ form.id }}
                    <div class="contact-form">{{ field.label_tag }} {{ field }}</div>
                {% endfor %}
            </div>    

            <div id="emty-form" class="">{{ formset.empty_form.as_p }}</div>
            <button id="add-more" type="button">Add more</button>
            <button id="save" type="submit" class="save btn btn-secondary">Save</button>
        {% endif %}
        
    </form>    
    </div>
    <script>
        
        const addMoreBtn = document.getElementById("add-more")
        const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')

        addMoreBtn.addEventListener('click', add_new_form)
        function add_new_form(event) {
            if (event) {
                event.preventDefault()
            }
            const currentContactForms = document.getElementsByClassName('contact-form')
            const currentFormCount = currentContactForms.length// + 1
            console.log(currentContactForms.length)
            const formCopyTarget = document.getElementById('contact-form-list')
            const copyEmptyFormEl = document.getElementById("emty-form").cloneNode(true)
            copyEmptyFormEl.setAttribute('class', 'contact-form')
            copyEmptyFormEl.setAttribute('id', `form-${currentFormCount}`)
            const regex = new RegExp('__prefix__', 'g')
            copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
            totalNewForms.setAttribute('value', currentContactForms + 1)
            formCopyTarget.append(copyEmptyFormEl)
        } 

    </script>-->

{% endblock content %}

resume/templates/resume/create_cv_personal_data.html
{% extends 'resume/base.html' %}
{% load static %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <div class="container">

    <h1>Личные данные</h1>
    <hr/>

    <form method="POST">
        {% csrf_token %}
        {{ pers_form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
          <button class="save btn btn-secondary">Save</button>
    </form>
    <p>{{ pos_id }}</p>

   </div>

</body>
</html>

{% endblock content %}

resume/templates/resume/create_cv_position.html
{% extends 'resume/base.html' %}
{% load static %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <div class="container">

    <h1>Укажите позицию</h1>
    <hr/>

    <form method="POST">
        {% csrf_token %}
        {{ position_form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>

   </div>

</body>
</html>

{% endblock content %}

resume/templates/resume/create_cv_references.html
{% extends 'resume/base.html' %}

{% block content %}

    <h2>Add references for {{ position.position_name }}</h2>
    <hr>

    <div class="container">
        <button type="button" hx-get="{% url 'resume:create-reference-form' position.id %}" hx-target="#referenceform" hx-swap="beforeend">
            Add reference
        </button>
    </div>

    <div id="referenceform" class="container"></div>

    <div class="container">
        {% for reference in references %}
            {% include 'resume/partials/reference_detail.html' %}
        {% endfor %}
    </div>

{% endblock content %}

resume/templates/resume/create_cv_skills.html
{% extends 'resume/base.html' %}
{% load static %}

{% block content %}

    <h2>Add skills for {{ position.position_name }}</h2>
    <hr>

    <div class="container">
        <button type="button" hx-get="{% url 'resume:create-skill-form' position.id %}" hx-target="#skillform" hx-swap="beforeend">
            Add skill
        </button>
    </div>

    <div id="skillform" class="container"></div>

    <div class="container">
        {% for skill in skills %}
            {% include 'resume/partials/skill_detail.html' %}
        {% endfor %}

        <div>
            <a href="{% url 'resume:create_cv_workexp' position.id %}">
                <button>Next</button>
            </a>
        </div>
    </div>


{% endblock content %}

resume/templates/resume/create_cv_workexp.html
{% extends 'resume/base.html' %}

{% block content %}

    <h2>Add work experience for {{ position.position_name }}</h2>
    <hr>

    <div class="container">
        <button type="button" hx-get="{% url 'resume:create-workexp-form' position.id %}" hx-target="#workexpform" hx-swap="beforeend">
            Add work experience
        </button>
    </div>

    <div id="workexpform" class="container"></div>

    <div class="container">
        {% for workexp in workexps %}
            {% include 'resume/partials/workexp_detail.html' %}
        {% endfor %}
    </div>

    <div>
        <a href="{% url 'resume:create_cv_references' position.id %}">
            <button>Next</button>
        </a>
    </div>

{% endblock content %}

resume/templates/resume/detail_cv.html
{% extends 'resume/base.html' %}

{% block content %}
    <div>
        <div hx-target="this" hx-swap="outerHTML">
            <div>
                <h1>CV for {{ position.position_name }}</h1>
            </div>
            <div>
                <button hx-get="{% url 'resume:update_position' position.id %}">Update</button>
            </div>
        </div>
    </div>

    <div>
        <div>
            {{ position.position_name }}
        </div>
        <div>
            <button>Update</button>
        </div>
    </div>

    <div>
        {% for pers_data in pers_datas %}
            <div>
                <div>
                    <p>{{ pers_data.first_name }} {{ pers_data.last_name }}</p>
                </div>
                <div>
                    <button>Update</button>
                </div>
            </div>
        {% endfor %}    
    </div>

    <div>
        {% for contact in contacts %}
            <div>
                <div>
                    <p>{{ contact.contact_label }}: {{ contact.contact_value }}</p>
                </div>
                <div>
                    <button>Update</button>
                    <button>Delete</button>
                </div>
            </div>
        {% endfor %}    
    </div>

    <div>
        <div>
            <h2>Skills</h2>
        </div>

        <div>
            {% for skill in skills %}
                <div>
                    <ul>
                        <li>{{ skill }}</li>
                        <div>
                            <button>Update</button>
                            <button>Delete</button>
                        </div>
                    </ul>
                </div>
            {% endfor %}    
        </div>
    </div>

    <div>
        <h2>Work experience</h2>
    </div>

    <div>
        {% for work_exp in work_exps %}
            <div>
                <div>
                    <p>{{ work_exp.company }} | {{ work_exp.date_of_employment }}-{{ work_exp.date_of_dismissal }}</p>
                </div>
                <div>
                    <p>
                        <a href="{{ work_exp.link_company }}">work_exp.link_company</a>
                    </p>
                </div>
                <div>
                    <p>{{work_exp.position_work}}</p>
                </div>
                <div>
                    <div>
                        <p>Description</p>
                    </div>
                    <div>
                        <p>{{ work_exp.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        
        <div>
            <div>
                <h2>Summary</h2>
            </div>
            
            <div>
                <p>{{ summary.summary }}</p>
            </div>
        </div>

        <div>
            <div>
                <h2>References</h2>
            </div>

            <div>
                <ol>
                    {% for reference in references %}
                    <div>
                        <li>{{ reference.ref_name }}: {{ reference.ref_link }}</li>                        
                    </div>
                    {% endfor %}
                </ol> 
            </div>
        </div>
    </div>

{% endblock content %}

resume/templates/resume/main_page.html
{% extends 'resume/base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'resume/css/styles.css' %}">
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <div class="container">
        <div class="create_cv_div">
            <div class="container text-center">
                <div class="row">
                    <div class="col">
                        <a href="{% url 'resume:create_cv_position' %}">
                            <button type="button" class="btn btn-outline-primary button_create-CV-on-main-page">
                                {{ menu.create_cv }}
                            </button>
                        </a>
                    </div>
                    <div class="col">
                        <div class="text-for-create-cv">
                            Create an impressive resume in just a few steps
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <p> Обратная связь</p>
        <form method="post">
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>

        {% block feedback_form %}
        {% endblock %}

        {% if user.is_authenticated %}
            <p>{{ user_id }}</p>
        {% endif %}
    </div>
    <div class="container">
        <h3>Links</h3>
        <div>
            <ul>
                <li>Add contacts: link</li>
            </ul>
        </div>
    </div>
    


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    

<!--    <p>Количество посещений: {{ num_visits }}</p>-->
</body>
</html>
{% endblock %}