config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('resume.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

resume/urls.py
from django.urls import path
from . import views


app_name = 'resume'
urlpatterns = [
    path('', views.main_page, name='main_page'),

    #paths for working with Position object
    path('create-cv-position/', views.create_cv_position, name='create_cv_position'),
    path('htmx/contact/<int:pos_id>/update/', views.update_position, name='update_position'),
    path('htmx/position/<int:pos_id>', views.detail_position, name='detail_position'),


    path('<str:username>/create-cv-pers-data/', views.create_cv_personal_data, name='create_cv_personal_data'),

    # paths for working with Contacts objects
    path('create-cv-contacts/<int:pk>', views.create_cv_contacts, name='create_cv_contacts'),
    path('htmx/contact/<pk>/', views.detail_contact, name="detail-contact"),
    path('htmx/contact/<pk>/update/', views.update_contact, name="update-contact"),
    path('htmx/contact/<pk>/delete/', views.delete_contact, name="delete-contact"),
    path('htmx/create-contact-form/<int:pk>/', views.create_contact_form, name='create-contact-form'),

    # paths for working with Skills objects
    path('create-cv-skills/<int:pk>', views.create_cv_skills, name='create_cv_skills'),
    path('htmx/skill/<pk>/', views.detail_skill, name="detail-skill"),
    path('htmx/skill/<pk>/update/', views.update_skill, name="update-skill"),
    path('htmx/skill/<pk>/delete/', views.delete_skill, name="delete-skill"),
    path('htmx/create-skill-form/<int:pk>/', views.create_skill_form, name='create-skill-form'),

    # paths for working with WorWorkExperience objects during creating CV
    path('create-cv-workexp/<int:pk>/', views.create_cv_workexp, name='create_cv_workexp'),
    path('htmx/workexp/<int:pk>/', views.detail_workexp, name="detail-workexp"),
    path('htmx/workexp/<int:pk>/update/', views.update_workexp, name="update-workexp"),
    path('htmx/workexp/<int:pk>/delete/', views.delete_workexp, name="delete-workexp"),
    path('htmx/create-workexp-form/<int:pk>/', views.create_workexp_form, name='create-workexp-form'),

    # paths for working with Referncess objects during creating CV
    path('create-cv-references/<int:pk>/', views.create_cv_references, name='create_cv_references'),
    path('htmx/reference/<int:pk>/', views.detail_reference, name="detail-reference"),
    path('htmx/reference/<int:pk>/update/', views.update_reference, name="update-reference"),
    path('htmx/reference/<int:pk>/delete/', views.delete_reference, name="delete-reference"),
    path('htmx/create-reference-form/<int:pk>/', views.create_reference_form, name='create-reference-form'),

    path('my-all-cv', views.get_all_cv, name='get_all_cv'),
    path('detail-cv/<int:pos_id>', views.get_detail_cv, name='get_detail_cv'),
]

users/urls.py
from django.urls import path, include

from users.views import Register

urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('register/', Register.as_view(), name='register'),
]

resume/forms.py
from users.models import User
from django import forms
from django.forms import ModelForm
import resume.models
import users
from django.forms.models import inlineformset_factory


class CreateCVPositionForm(ModelForm):
    ''' Создает форму для позиции '''
    
    class Meta:
        model = resume.models.Position
        fields = '__all__'
        exclude = ('created_by', )


class CreateCVPersonalDataForm(ModelForm):
    ''' Создает форму для персональных данных '''
    
    class Meta:
        model = resume.models.PersonalData
        fields = ('first_name', 'last_name')


class CreateCVContactForm(forms.ModelForm):
    ''' form for COntacts object '''

    class Meta:
        model = resume.models.Contacts
        fields = (
            'contact_label',
            'contact_value'
        )


class CreateCVSkillForm(forms.ModelForm):
    ''' form for Skills object '''

    class Meta:
        model = resume.models.Skills
        fields = ('skill', )


class CreateCVWorkExperienceForm(forms.ModelForm):
    ''' form for WorkExperience object '''

    class Meta:
        model = resume.models.WorkExperience
        fields = ('company',
                  'position_work',
                  'link_company',
                  'date_of_employment',
                  'date_of_dismissal',
                  'description')
        

class CreateCVReferencesForm(forms.ModelForm):
    ''' form for References object '''

    class Meta:
        model = resume.models.References
        fields = ('ref_name',
                  'ref_link')

resume/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseNotAllowed, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import *

from .forms import (
    CreateCVPositionForm,
    CreateCVContactForm,
    CreateCVSkillForm,
    CreateCVPersonalDataForm,
    CreateCVWorkExperienceForm,
    CreateCVReferencesForm,
)

from my_feedback.forms import FeedBackForm
import resume.forms
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.forms.models import modelformset_factory


menu = {
    'create_cv': 'Create CV'
}

def main_page(request):
    ''' Рендерит главную страницу '''

    form = FeedBackForm
    username = request.user.username

    # количество посещений
    # num_visits = request.session.get('num_visits', 0)
    # request.session['num_visits'] = num_visits + 1

    context = {
        'menu': menu,
        'title': 'Main page',
        'form': form,
        'username': username}
    
    return render(request, 'resume/main_page.html', context=context)


@login_required(login_url='/users/login/')
def create_cv_position(request):
    ''' ренедрит форму для внесения позиции '''

    username = request.user.username
    
    if request.method == 'POST':
        position_form = resume.forms.CreateCVPositionForm(request.POST)
        if position_form.is_valid():
            position_form = position_form.save(commit=False)
            position_form.created_by = request.user
            position_form.save()
            return redirect('resume:create_cv_personal_data', username)

    position_form = CreateCVPositionForm()
    context = {
        'position_form': position_form,
        'username': username}

    return render(request, "resume/create_cv_position.html", context)


def update_position(request, pos_id):
    position = get_object_or_404(Position, id=pos_id)
    position_form = CreateCVPositionForm()

    if request.method == 'POST':
        if position_form.is_valid():
            position_form.save()

    context = {
        'position': position,
        'position_form': position_form
    }

    return render(request, 'resume/partials/position_form.html', context)


def detail_position(request, pos_id):
    position = get_object_or_404(Position, id=pos_id)

    context = {
        'position': position
    }

    return render(request, 'resume/partials/position_detail.html', context)


@login_required(login_url='/users/login/')
def create_cv_personal_data(request, username):
    ''' Получает поля из всех моделей для формы / создания резюме '''

    username = request.user.username
    last_pos = Position.objects.all().last()
    
    if request.method == 'POST':
        pers_form = resume.forms.CreateCVPersonalDataForm(request.POST)
        if pers_form.is_valid():
            pers_form = pers_form.save(commit=False)
            pers_form.pos = last_pos
            pers_form.save()
            # TODO: удалить дубликаты
            return redirect('resume:create_cv_contacts', pk=last_pos.id)

    pers_form = resume.forms.CreateCVPersonalDataForm()
    context = {
        'pers_form': pers_form}

    return render(request, "resume/create_cv_personal_data.html", context)


@login_required(login_url='/users/login/')
def create_cv_contacts(request, pk):
    ''' functions for working with models.Contacts '''

    position = Position.objects.get(id=pk)
    contacts = Contacts.objects.filter(pos=position)
    form = CreateCVContactForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            contact = form.save(commit=False)
            contact.pos = position
            contact.save()
            pk = contact.pk
            return redirect("resume:detail-contact", pk) # here i do redirect
        else:
            return render(request, "resume/partials/contact_form.html", context={
                "form": form
            })

    context = {
        "form": form,
        "position": position,
        "contacts": contacts,
        'title': 'Add contacts'
    }

    return render(request, "resume/create_cv_contacts.html", context)


@login_required(login_url='/users/login/')
def update_contact(request, pk):
    contact = Contacts.objects.get(id=pk)
    form = CreateCVContactForm(request.POST or None, instance=contact)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("resume:detail-contact", pk=contact.id)

    context = {
        "form": form,
        "contact": contact
    }

    return render(request, "resume/partials/contact_form.html", context)


@login_required(login_url='/users/login/')
def delete_contact(request, pk):
    contact = get_object_or_404(Contacts, id=pk)

    if request.method == "POST":
        contact.delete()
        return HttpResponse("")

    return HttpResponseNotAllowed(
        [
            "POST",
        ]
    )


@login_required(login_url='/users/login/')
def detail_contact(request, pk):
    ''' view for rendering added Contact to DB and displaying it on 'resume/create_cv_contact.html' template '''

    contact = get_object_or_404(Contacts, pk=pk)
    context = {
        "contact": contact
    }
    return render(request, "resume/partials/contact_detail.html", context)


@login_required(login_url='/users/login/')
def create_contact_form(request, pk):
    form = CreateCVContactForm()
    position = {"id": pk}
    context = {
        "form": form,
        "position": position,
    }
    return render(request, "resume/partials/contact_form.html", context)



''' views for working with Skills object during creating CV using forms '''

@login_required(login_url='/users/login/')
def create_cv_skills(request, pk):
    ''' main views for displaying form for to add skills to CV and redirect to HTMX template '''

    position = Position.objects.get(id=pk)
    skills = Skills.objects.filter(pos=position)
    form = CreateCVSkillForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            skill = form.save(commit=False)
            skill.pos = position
            skill.save()
            pk = skill.pk
            return redirect("resume:detail-skill", pk)
        else:
            return render(request, "resume/partials/skill_form.html", context={
                "form": form
            })

    context = {
        "form": form,
        "position": position,
        "skills": skills,
        'title': 'Add skills'
    }

    return render(request, "resume/create_cv_skills.html", context)


@login_required(login_url='/users/login/')
def create_skill_form(request, pk):
    ''' view for rendering form of instnce of Skills object for adding skills during creating CV '''

    form = CreateCVSkillForm()
    position = {"id": pk}
    context = {
        "form": form,
        "position": position,
    }
    return render(request, "resume/partials/skill_form.html", context)


@login_required(login_url='/users/login/')
def detail_skill(request, pk):
    ''' view for rendering added skill to DB and displaying it on 'resume/create_cv_skills.html' template '''

    skill = get_object_or_404(Skills, pk=pk)
    context = {
        "skill": skill
    }
    return render(request, "resume/partials/skill_detail.html", context)


@login_required(login_url='/users/login/')
def update_skill(request, pk):
    ''' view for updating added skill '''

    skill = Skills.objects.get(id=pk)
    form = CreateCVSkillForm(request.POST or None, instance=skill)
    position = {'id': skill.pos_id}
    print(position)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("resume:detail-skill", pk=skill.id)

    context = {
        "form": form,
        "skill": skill,
        'position': position
    }

    return render(request, "resume/partials/skill_form.html", context)


@login_required(login_url='/users/login/')
def delete_skill(request, pk):
    ''' view for delete instance of Skills object '''

    skill = get_object_or_404(Skills, id=pk)

    if request.method == "POST":
        skill.delete()
        return HttpResponse("")

    return HttpResponseNotAllowed(
        [
            "POST",
        ]
    )




''' views for working with WorkExperience object during creating CV using forms '''

@login_required(login_url='/users/login/')
def create_cv_workexp(request, pk):
    ''' main views for displaying form for to add WorkExperience to CV and redirect to HTMX template '''

    position = Position.objects.get(id=pk)
    workexps = WorkExperience.objects.filter(pos=position)
    form = CreateCVWorkExperienceForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            workexp = form.save(commit=False)
            workexp.pos = position
            workexp.save()
            pk = workexp.pk
            return redirect("resume:detail-workexp", pk=pk)
        else:
            return render(request, "resume/partials/workexp_form.html", context={
                "form": form,
                'position': position
            })

    context = {
        "form": form,
        "position": position,
        "workexps": workexps,
        'title': 'Add company'
    }

    return render(request, "resume/create_cv_workexp.html", context)


@login_required(login_url='/users/login/')
def create_workexp_form(request, pk):
    ''' view for rendering form of WorkExperience object for adding instnce during creating CV '''

    form = CreateCVWorkExperienceForm()
    position = {"id": pk}
    context = {
        "form": form,
        "position": position,
    }
    return render(request, "resume/partials/workexp_form.html", context)


@login_required(login_url='/users/login/')
def detail_workexp(request, pk):

resume/templates/resume/partials/contact_detail.html
<div hx-target="this" class="mt-3 py-3 px-3 bg-white shadow border border-gray-100">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
        Contact label: {{ contact.contact_label }}
    </h3>
    <p class="text-gray-600">Contact: {{ contact.contact_value }}</p>
    <div class="mt-2">
        <button hx-get="{% url 'resume:update-contact' contact.id %}" hx-swap="outerHTML"
            class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Update
        </button>
        <button hx-post="{% url 'resume:delete-contact' contact.id %}" hx-swap="outerHTML swap:1s"
            class="ml-2 inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
            Delete
        </button>
    </div>
</div>

resume/templates/resume/partials/contact_form.html
{% load tailwind_filters %}

<div hx-target="this" hx-swap="outerHTML" class="mt-3 py-3 px-3 bg-white shadow border border-gray-100">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        {% if contact %}
        <button type="submit" hx-post="{% url 'resume:update-contact' contact.id %}"
            class="inline-flex items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Submit
        </button>
        <button hx-get="{% url 'resume:detail-contact' contact.id %}" type="button"
            class="ml-2 inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Cancel
        </button>
        {% else %}
            <button type="submit" hx-post="{% url 'resume:create_cv_contacts' position.id %}"
            class="inline-flex items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Submit
        </button>
        {% endif %}
    </form>
</div>

resume/templates/resume/partials/position_detail.html
<div hx-target="this">
    <p>{{ position.position_name }}</p>
    <div class="mt-2">
        <button hx-get="{% url 'resume:update_position' position.id %}" hx-swap="outerHTML">
            Update
        </button>
        <!-- <button hx-post="{% url 'resume:delete-contact' contact.id %}" hx-swap="outerHTML swap:1s"
            class="ml-2 inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
            Delete
        </button> -->
    </div>
</div>

resume/templates/resume/partials/position_form.html
<div hx-target="this" hx-swap="outerHTML">
    <form method="POST">
        {% csrf_token %}
        {% if position %}
        <button type="submit" hx-post="{% url 'resume:update_position' position.id %}">
            Submit
        </button>
        <button hx-get="{% url 'resume:detail_position' position.id %}" type="button">
            Cancel
        </button>
        {% else %}
            <button type="submit" hx-post="{% url 'resume:get_detail_cv' position.id %}">
            Submit
        </button>
        {% endif %}
    </form>
</div>

resume/templates/resume/partials/reference_detail.html
<div hx-target="this" class="mt-3 py-3 px-3 bg-white shadow border border-gray-100">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
        {{ reference.ref_name }}: {{ reference.ref_link }}
    </h3>
    <div class="mt-2">
        <button hx-get="{% url 'resume:update-reference' reference.id %}" hx-swap="outerHTML"
            class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Update
        </button>
        <button hx-post="{% url 'resume:delete-reference' reference.id %}" hx-swap="outerHTML swap:1s"
            class="ml-2 inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
            Delete
        </button>
    </div>
</div>

resume/templates/resume/partials/reference_form.html
{% load tailwind_filters %}

<div hx-target="this" hx-swap="outerHTML" class="mt-3 py-3 px-3 bg-white shadow border border-gray-100">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        {% if reference %}
        <button type="submit" hx-post="{% url 'resume:update-reference' reference.id %}"
            class="inline-flex items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Submit
        </button>
        <button hx-get="{% url 'resume:detail-reference' reference.id %}" type="button"
            class="ml-2 inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Cancel
        </button>
        {% else %}
            <button type="submit" hx-post="{% url 'resume:create_cv_references' position.id %}"
            class="inline-flex items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Submit
        </button>
        {% endif %}
    </form>
</div>

resume/templates/resume/partials/skill_detail.html
<div hx-target="this" class="container">
    Skill: {{ skill.skill }}

    <div>
        <button hx-get="{% url 'resume:update-skill' skill.id %}" hx-swap="outerHTML">
            Update
        </button>

        <button hx-post="{% url 'resume:delete-skill' skill.id %}" hx-swap="outerHTML swap:1s">
            Delete
        </button>
    </div>
</div>

resume/templates/resume/partials/skill_form.html
<!-- {% load tailwind_filters %} -->

<div class="container" style="margin-left: 20px;">
    <div hx-target="this" hx-swap="outerHTML">
        <form class="shadow p-3 mb-5 bg-body-tertiary rounded" method="POST">
            {% csrf_token %}
            {{ form.as_p }}   
            {% if contact %}
            <button type="submit" hx-post="{% url 'resume:update-skill' skill.id %}">
                Submit
            </button>
            <button hx-get="{% url 'resume:detail-skill' skill.id %}" type="button">
                Cancel
            </button>
            {% else %}
            <!-- <button type="submit" hx-post="." -->
                <button type="submit" hx-post="{% url 'resume:create_cv_skills' position.id %}">
                Submit
            </button>
            {% endif %}
        </form>
    </div>
</div>

resume/templates/resume/partials/workexp_detail.html
<div hx-target="this" class="mt-3 py-3 px-3 bg-white shadow border border-gray-100">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
        Company: {{ workexp.company }}
    </h3>
    <p class="text-gray-600">Position: {{ workexp.position_work }}</p>
    <div class="mt-2">
        <button hx-get="{% url 'resume:update-workexp' workexp.id %}" hx-swap="outerHTML"
            class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Update
        </button>
        <button hx-post="{% url 'resume:delete-workexp' workexp.id %}" hx-swap="outerHTML swap:1s"
            class="ml-2 inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
            Delete
        </button>
    </div>
</div>

resume/templates/resume/partials/workexp_form.html
{% load tailwind_filters %}

<div hx-target="this" hx-swap="outerHTML" class="mt-3 py-3 px-3 bg-white shadow border border-gray-100">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        {% if workexp %}
        <button type="submit" hx-post="{% url 'resume:update-workexp' workexp.id %}"
            class="inline-flex items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Submit
        </button>
        <button hx-get="{% url 'resume:detail-workexp' workexp.id %}" type="button"
            class="ml-2 inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Cancel
        </button>
        {% else %}
            <button type="submit" hx-post="{% url 'resume:create_cv_workexp' position.id %}"
            class="inline-flex items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Submit
        </button>
        {% endif %}
    </form>
</div>